from database import db


class Car(db.Model):
    __tablename__ = 'cars'
    id = db.Column(db.String, primary_key=True)
    url = db.Column(db.String, nullable=False)
    country = db.Column(db.String, nullable=False)
    brand = db.Column(db.String, nullable=False, index=True)
    model = db.Column(db.String, nullable=False, index=True)
    price = db.Column(db.Integer, nullable=False)
    km = db.Column(db.Integer, nullable=False)
    title = db.Column(db.String, nullable=True)
    description = db.Column(db.String, nullable=True)
    registration = db.Column(db.String, nullable=True)
    power = db.Column(db.Float, nullable=True)
    gear = db.Column(db.String, nullable=True, index=True)
    gas = db.Column(db.String, nullable=True, index=True)
    body = db.Column(db.String, nullable=True, index=True)
    category = db.Column(db.String, nullable=True)
    drive = db.Column(db.String, nullable=True, index=True)
    seats = db.Column(db.Integer, nullable=True, index=True)
    doors = db.Column(db.Integer, nullable=True, index=True)
    buildyear= db.Column(db.Integer, nullable=True)
    apk = db.Column(db.String, nullable=True)
    capacity = db.Column(db.Integer, nullable=True)
    gears = db.Column(db.Integer, nullable=True, index=True)
    cylinders = db.Column(db.Integer, nullable=True, index=True)
    consumption = db.Column(db.Float, nullable=True)
    co2 = db.Column(db.Integer, nullable=True)
    emission = db.Column(db.String, nullable=True)
    sticker = db.Column(db.Integer, nullable=True)
    electricity = db.Column(db.Float, nullable=True)
    seller = db.Column(db.String, nullable=True)
    maintenance = db.Column(db.String, nullable=True)
    color = db.Column(db.String, nullable=True)
    org_color = db.Column(db.String, nullable=True)
    varnish = db.Column(db.String, nullable=True)
    date_listing = db.Column(db.Integer, nullable=True)
    date_sold = db.Column(db.Integer, nullable=True)
    score = db.Column(db.Integer, nullable=True)
    warranty = db.Column(db.Integer,nullable=True)
    origin = db.Column(db.String, nullable=True)
    ad_number = db.Column(db.String, nullable=True)
    name_seller = db.Column(db.String, nullable=True)
    location = db.Column(db.String, nullable=True)
    zombie = db.Column(db.Integer, nullable=True)
    broken = db.Column(db.Integer, nullable=True)
